### ISSUE TITLE
UI consistency

### ISSUE THREAD

**Issue by mandeep** [tarkah/tickrs#111]
Hi @tarkah,

First let me say this is a really cool project and I hope to contribute some effort into it.

At first glance I noticed a few things that seem a bit off:
  - The words in the Toggle box are all capitalized, but things like current price, high, and low are lowercased. The same goes for the words in the Options pane as well. I think there should be some consistency where these words are all capitalized. 
  - The c, h, and l letters do their job. One consistency change would be to spell them out to Current Price, High, Low.
  - In the Toggle box, the 'c' keybind should show the current chart type rather than the next chart type. This would be parity with other trading software.
  - When entering a ticker in lowercase, the ticker shows up in the Tabs section as all lowercased. I think they should be all uppercased.

Most of these are not issues, mostly just personal preferences from what I've seen in other charting software. If these sound like changes you'd like to see, let me know and I'd be happy to submit a PR.

**Comment by tarkah** [comment]
@mandeep Thanks for opening this up. I'd absolutely love the contributions, so feel free! I think these are great suggestions.

If you want to take a stab, here's a few spots to get you started:

- Toggle box is rendered here: https://github.com/tarkah/tickrs/blob/d7c6b54bef11cc03cdcd649466461274eddd9fe3/src/widget/stock.rs#L721
- This is where the add stock symbol is submitted to created a new widget: https://github.com/tarkah/tickrs/blob/d7c6b54bef11cc03cdcd649466461274eddd9fe3/src/widget/add_stock.rs#L43
