### ISSUE TITLE
Create a Homebrew formula

### ISSUE THREAD

**Issue by VDuchauffour** [tarkah/tickrs#113]
Hi,

It could be a good idea to create a homebrew formula for MacOS users.

Thanks,
Vincent

**Comment by tarkah** [comment]
I think that'd be great. Unfortunately I do not have a macos device, so it'd be awesome if someone from the community could open a PR for that.

**Comment by miraclx** [comment]
I don't have a macOS device either, but https://github.com/fastai/fastmac.

Gets you an SSH into GitHub Actions macs.

**Comment by casperstorm** [comment]
I can help you guys.

Do you want it on `homebrew/core` or your own tap? 
I would properly just suggest your own tap so you can update it without worrying about having someone review it every time.

Then you can do something like:
```
brew tap tarkah/tickrs
brew install tickrs
```

If you want to go this road, this is basically what we need to do: https://federicoterzi.com/blog/how-to-publish-your-rust-project-on-homebrew/
If you want it on `homebrew/core` it requires a little more work, tests etc: https://docs.brew.sh/Formula-Cookbook#an-introduction

It is, imho, much easier to just create your own tap. I can help with it if needed, just let me know.

**Comment by tarkah** [comment]
Thanks, @casperstorm! Sounds like tap is the way to go, seems super easy.

I can probably put that together myself, but it'd be great if you could help test.

**Comment by casperstorm** [comment]
> Thanks, @casperstorm! Sounds like tap is the way to go, seems super easy.
> 
> I can probably put that together myself, but it'd be great if you could help test.

I agree, then you also have the control. Just let me know when to test/review.

**Comment by tarkah** [comment]
@casperstorm Ok, can you test?

```
brew tap tarkah/tickrs
brew install tickrs
```

**Comment by tarkah** [comment]
I've set up the repo here: https://github.com/tarkah/homebrew-tickrs

And I plan on adding this to my actions of this repo to bump that via PR:

https://github.com/mislav/bump-homebrew-formula-action

**Comment by tarkah** [comment]
@VDuchauffour Ok, this has been created. You can install via the following. I've added this to the README and will update moving forward

```
brew tap tarkah/tickrs
brew install tickrs
```

**Comment by VDuchauffour** [comment]
@tarkah thanks for quick response ! but I get this error `tickrs: no bottle available!` when i try to install after the `tap`command

**Comment by tarkah** [comment]
Hmm... @casperstorm can you try again? I updated the repo for `v0.14.1` and maybe that broke something? Or maybe you know what the issue here is?

**Comment by miraclx** [comment]
Works just fine on my end. Great job!

With `tickrs --version` verified to be `v0.14.1`.

**Comment by miraclx** [comment]
An aside: I noticed `tickrs` couldn't capture <kbd>shift</kbd>+<kbd>left/right</kbd> within the SSH session, but it correctly registers <kbd>shift</kbd>+<kbd>[char]</kbd>, <kbd>shift</kbd>+<kbd>tab</kbd> and <kbd>left/right</kbd> individually.

Please confirm this if is reproducible behavior in macOS itself, otherwise, I guess, it's something wrong at my end, either with SSH or tmux.

If you're wondering where <kbd>shift</kbd>+<kbd>left/right</kbd> can be used, see the `kagi` chart.

**Comment by VDuchauffour** [comment]
Ok so I was able to install tickrs with that command `brew install tarkah/tickrs/tickrs` after the `tap` command.
It's strange because `brew info tickrs` is fine (tickrs' version is set to 0.14.0 as stable). Maybe something related to the yml workflow file ?
I get 0.14.1 as version with the same command that @miraclx
