### ISSUE TITLE
Unable to track U.S. Dollar Index

### ISSUE THREAD

**Issue by Maskhjarna** [tarkah/tickrs#114]
I'm unable to add USDX (Yahoo! Finance quote DX-Y.NYB) under symbols. I've added it under symbols like so:
```yml
symbols:
    - BTC-USD
    - ETH-USD
    - ADA-USD
    - LINK-USD
    - BTC-ETH
    - DX-Y.NYB
```
and the graph seems to be stuck loading the graph. If indexes are supposed to be added differently it isn't made clear by the documentation.

![image](https://user-images.githubusercontent.com/80115848/110140301-3de6b280-7dd4-11eb-84ad-fce14842735f.png)

Thanks! - Gustav

**Comment by tarkah** [comment]
Thanks for opening the issue! Hmm, that symbol definitely works when I query the API directly with it. There must be a missing value from the response that I'm expecting that doesn't exist on indexes. I'll get this fixed.

**Comment by tarkah** [comment]
Yup, as suspected it was a simple fix. There was a couple fields that aren't coming across for Index tickers. Working with #115:

![image](https://user-images.githubusercontent.com/10239377/110152063-1a047c00-7d96-11eb-9574-ff6258f2dee8.png)


I'll get a new release out today w/ this fix
