### ISSUE TITLE
Provide command line option to select time resolution at startup

### ISSUE THREAD

**Issue by daniel-j-h** [tarkah/tickrs#12]
Hey hey :wave:

It would be amazing to be able to select the time resolution from the command line already.

For example: you have a raspberry pi zero with a display and want it to start up with a specific time resolution automatically on boot.

**Comment by tarkah** [comment]
Great idea, I'll get this one added no problem!

**Comment by tarkah** [comment]
New option added as:

```
-t, --time-frame <time-frame>              Use specified time frame when starting program and when new stocks are
                                           added [default: 1D]  [possible values: 1D, 1W, 1M, 3M, 6M, 1Y, 5Y]
```

**Comment by daniel-j-h** [comment]
Oh wow, that was quick! :hugs: Thanks! :bow:
