### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by gaming-hacker** [tarkah/tickrs#122]
Hi,
Can you add in your readme some basic build instructions for non "go" people? ldflags, etc

**Comment by tarkah** [comment]
It's actually a Rust program!

Install rust https://www.rust-lang.org/tools/install

Then `cargo build --release`. Binary will be located in `target/release/tickrs`. Super easy!

**Comment by gaming-hacker** [comment]
Great thanks for that.

**Comment by gaming-hacker** [comment]
Anyone else get this error building on OSX 10.13 or 10.14?

The following warnings were emitted during compilation:

warning: curl/lib/connect.c: In function 'singleipconnect':
warning: curl/lib/connect.c:1253:10: warning: implicit declaration of function '__builtin_available'; did you mean '__builtin_scalbl'? [-Wimplicit-function-declaration]
warning:  1253 |       if(__builtin_available(macOS 10.11, iOS 9.0, tvOS 9.0, watchOS 2.0, *)) {
warning:       |          ^~~~~~~~~~~~~~~~~~~
warning:       |          __builtin_scalbl
warning: curl/lib/connect.c:1253:30: error: 'macOS' undeclared (first use in this function)
warning:  1253 |       if(__builtin_available(macOS 10.11, iOS 9.0, tvOS 9.0, watchOS 2.0, *)) {
warning:       |                              ^~~~~
warning: curl/lib/connect.c:1253:30: note: each undeclared identifier is reported only once for each function it appears in
warning: curl/lib/connect.c:1253:35: error: expected ')' before numeric constant
warning:  1253 |       if(__builtin_available(macOS 10.11, iOS 9.0, tvOS 9.0, watchOS 2.0, *)) {
warning:       |                                   ^~~~~~
warning:       |                                   )

error: failed to run custom build command for `curl-sys v0.4.40+curl-7.75.0`

**Comment by gaming-hacker** [comment]
I think it should be macOSX not macOS.

**Comment by tarkah** [comment]
Hmm not sure.

I do have a release for macos you can download:

https://github.com/tarkah/tickrs/releases/download/v0.14.4/tickrs-v0.14.4-x86_64-apple-darwin.tar.gz

**Comment by gaming-hacker** [comment]
Thanks but that works for OSX 10.15+, I have 10.13 and 10.14

**Comment by tarkah** [comment]
Ahh, I see. Were you able to figure it out? I can add a feature flag to disable building static curl and instead have it dynamically link to your systems curl, which should fix the issue for you.
