### ISSUE TITLE
Deleted release?

### ISSUE THREAD

**Issue by orhun** [tarkah/tickrs#127]
A few hours ago I saw `tickrs` has a new release (`0.14.5`) and for that reason I updated the [Arch Linux package](https://archlinux.org/packages/community/x86_64/tickrs/). Now I see that release is gone from the repository. Is everything okay?

**Comment by tarkah** [comment]
Yeah I prematurely released a feature I wasn't 100% on. Sorry for the confusion!

**Comment by orhun** [comment]
In such case I'd expect seeing a new (minor) release that fixes/reverts the unfinished changes instead of straight up deletion. Please keep in mind that Arch Linux users can install the _latest_ (in this case, deleted) release after it's packaged. Also the package is marked as [unreproducible](https://reproducible.archlinux.org/api/v0/builds/103236/log) since the source is not accessible anymore.

Best thing to do here is skipping the deleted tag for your next release.

**Comment by tarkah** [comment]
Yeah that's my bad, totally forgot there was some actual packaging set up. I'll definitely make sure to skip to the next version.
