### ISSUE TITLE
Candlesticks not displayed

### ISSUE THREAD

**Issue by piotryordanov** [tarkah/tickrs#128]
Candlesticks are not displayed as in the demo gif.

I'm running ARCH on WSL2 inside alacrity terminal. Any idea why?

![image](https://user-images.githubusercontent.com/48773775/122694184-41982b00-d245-11eb-969c-98e64be369e6.png)

**Comment by piotryordanov** [comment]
![image](https://user-images.githubusercontent.com/48773775/122694386-d4d16080-d245-11eb-9101-8219d5e357b5.png)
Running it on windows with windows terminal, the candles are displayed, however there is a 'gap' inside a candle.

**Comment by tarkah** [comment]
@piotryordanov Each terminal / font causes things to look slightly different. I've used the following settings on Windows to get things to render properly...

- Use [alacritty](https://github.com/alacritty/alacritty) as the terminal. I couldn't get things to render perfectly in Windows Terminal
- In `%APPDATA%\alacritty\alacritty.yml` set the following option:

```yml
font:
  offset:
    x: 0
    y: -1
```

With this set, `tickrs` line and candle charts render perfectly!

**Comment by piotryordanov** [comment]
I confirm that alacritty on windows actually makes it render well. Thx :)
