### ISSUE TITLE
Latest release no longer working on Ubuntu Bionic

### ISSUE THREAD

**Issue by pataquets** [tarkah/tickrs#141]
When running latest `tickrs` binary (0.14.8-x86_64-unknown-linux) the following errors appear:
```
./tickrs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by ./tickrs)
./tickrs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./tickrs)
./tickrs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./tickrs)
./tickrs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./tickrs)
./tickrs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./tickrs)
```
I'm aware of Ubuntu Bionic being quite old. Just wondering if an easily toggled switch somewhere could enable a static build, which might solve this (not sure, thou).

**Comment by tarkah** [comment]
You can just use https://github.com/tarkah/tickrs/releases/tag/v0.14.6 for now. 

`v0.14.8` doesn't have any new features, it's just a re-release w/ updated dependencies. The github CI runners used to draft the release must be newer, so this will be an issue for all versions going forward. 

I do not plan on using older runners for compatibility here. You can always `cargo install --git https://github.com/tarkah/tickrs` to build it locally. Or request to have it packaged it for your distro.
