### ISSUE TITLE
Provide option to hide the toggle shortcuts

### ISSUE THREAD

**Issue by daniel-j-h** [tarkah/tickrs#24]
Hey hey :wave: At the moment we always show the "Toggle" shortcuts on the top right.

There is an option to not show the help, but there is no option to hide this toggle menu. For non-interactive use-cases like running on a raspberry pi with a small display attached, but no keyboard, it would be great if we could hide the toggle shortcuts.

Maybe `--hide-help` could just remove these, too?

**Comment by tarkah** [comment]
Great idea! I'll get this added.

**Comment by tarkah** [comment]
Ahhh, much better :)

![image](https://user-images.githubusercontent.com/10239377/92957449-68574480-f41d-11ea-9cda-699e7d97cb39.png)
