### ISSUE TITLE
Background color issues

### ISSUE THREAD

**Issue by tarkah** [tarkah/tickrs#25]
@daniel-j-h I noticed in your screenshots that there was weird coloring going on in places with the background. I've found the issue and will be fixing it, see my before and after.

![image](https://user-images.githubusercontent.com/10239377/92956279-7a37e800-f41b-11ea-85e9-e9cc0602e5fe.png)

![image](https://user-images.githubusercontent.com/10239377/92956225-5e344680-f41b-11ea-91a9-ba8b1b356e14.png)

**Comment by daniel-j-h** [comment]
:open_mouth: dang, this is awesome! :bow:
