### ISSUE TITLE
Toggle between different chart type (e.g. candlestick chart)

### ISSUE THREAD

**Issue by daniel-j-h** [tarkah/tickrs#30]
Hey hey :wave: I'm unsure about the charting library's limitations, but would it be possible to have e.g a candlestick plot type?

Should the user then be able to toggle between the charts and have a command line option to start with a specific chart type pre-selected? Just some ideas :hugs:

**Comment by tarkah** [comment]
Hmm, definitely not something supported out of the box but could potentially be hacked together. The library also provides a Canvas I'm sure it's possible to build my own using that. 

I like this idea as I like using candle charts as well, plus the API already gives me Open/Close/Low/High info. My biggest concern is guaranteeing all of the candlesticks will fit on the x axis depending on terminal size. So I either would have to implement a minimum screen width for that chart type and/or widen the intervals so there are less datapoints.
