### ISSUE TITLE
Stocks added on the Summary view default to 1D even if the summary is set to a different duration

### ISSUE THREAD

**Issue by dimo414** [tarkah/tickrs#35]
Here's an example of what I mean:

![Screenshot](https://user-images.githubusercontent.com/1885701/102748586-4d974480-4317-11eb-88ce-a1d62808f016.png)

To reproduce:

* Add one or more stocks on the detail view, then press `s` to go to the summary
* Swap to a different duration, e.g. 5Y
* Add another stock via `/` on the summary view
* Added stock will display 1D data until a new duration is selected (notice the open-price horizontal line which only displays on 1D charts)

**Comment by tarkah** [comment]
Thanks for opening the issue, good catch! I'll get this fixed asap.
