### ISSUE TITLE
Not sure if bug, can't see pre/post graph like in the demo.

### ISSUE THREAD

**Issue by dkowis** [tarkah/tickrs#42]
On the hypetrain! :gem: :raised_hands: 

But seriously, I don't see the dim color for the differentiation between pre/post, do I have something configured wrong?

It's alacritty on PopOS! 20.10
![image](https://user-images.githubusercontent.com/28048/106530807-9fa0bd80-64b2-11eb-8154-73b0544e75a5.png)

**Comment by tarkah** [comment]
💎🙌🚀

Can you try different colors and see if the problem persists? If you run the following, is "GRAY" visible?

```
echo -e "\033[1;30mGRAY"
```

It seems your Gray color and terminal background are the same color, so it is indistinguishable. At least that's my hunch!

**Comment by dkowis** [comment]
GRAY is barely visible, but it's not at all visible in the app...

![image](https://user-images.githubusercontent.com/28048/106532411-c44a6480-64b5-11eb-84b0-58abae2327fc.png)

**Comment by tarkah** [comment]
Hmm, maybe I'm using the wrong code. I'm trying to figure out what `Color::DarkGray` (the color I'm using in the TUI library) actually resolves to

**Comment by dkowis** [comment]
So there is something fishy with my color scheme, I was using solarized dark from here: https://github.com/alacritty/alacritty/wiki/Color-schemes#solarized

I switched to "afterglow" from the same site and it works:
![image](https://user-images.githubusercontent.com/28048/106532759-679b7980-64b6-11eb-8baf-b4c9449bf48d.png)

**Comment by tarkah** [comment]
Looks good! I'm 99% sure it's just the theme that's the problem, so I'm going to go ahead and close this. Hope you're enjoying the app!

**Comment by dkowis** [comment]
Yeah, it's definitely the theme, switching to a new one! Thanks.
