### ISSUE TITLE
Add stock shortcut '/' not working

### ISSUE THREAD

**Issue by rTfact** [tarkah/tickrs#45]

**Comment by tarkah** [comment]
Interesting. I'll see if I can add that "shift7" to the key bindings. Since you're running from source, you can hopefully test for me before I merge it.

**Comment by tarkah** [comment]
Original title:

>Add ticker via "/" doesn't seem to work on Win10 running in Windows Terminal. I'm running an Enterprise Windows with Danish keyboard so "/" is "shift 7". It works on the same machine running under WSL2/Ubuntu 20.04. In both instances it is compiled/installed using cargo install.❯ cargo --version cargo 1.49.0 (d00d64df9 2020-12-05)

**Comment by tarkah** [comment]
@rTfact The program has a debug mode that you can activate.... can you run with `SHOW_DEBUG=1 tickrs` and press `/` and tell me what the value of the debug window is. For example, this is what I see when I hit `/`.

```
DebugInfo { ..., last_event: Some(Key(KeyEvent{ code: Char('/'), modifiers: NONE }))  }
```

**Comment by tarkah** [comment]
@rTfact can you please provide the debug info I requested? Otherwise I'll be closing this issue.
