### ISSUE TITLE
Price history stretches to fit the timespan

### ISSUE THREAD

**Issue by Slickytail** [tarkah/tickrs#46]
If you try to view a timespan longer than the available data for an asset, the longest available history will be shown instead, but with no indication that it is being stretched. 

![20210205_10h33m51s_grim](https://user-images.githubusercontent.com/8876925/107054161-ac315880-67c7-11eb-9d84-80bb7b402977.png)
![20210205_10h34m07s_grim](https://user-images.githubusercontent.com/8876925/107054183-b3f0fd00-67c7-11eb-87da-c976bbe7e325.png)

For example, THNQ has existed for only about 9 months -- but attempting to view 5Y of its history gives no indication of this. This is not an issue when labels are visible, but it could be misleading in the summary view as there is no indication that different assets are not shown on the same timescale.

**Comment by tarkah** [comment]
Ok, I think I found a very reliable solution to make sure non-1D graphing is accurate... How does this look?

![Code_5GhuJ2T8my](https://user-images.githubusercontent.com/10239377/107079422-b42bd100-67a4-11eb-8842-0b8fe289cdae.png)
![Code_zSoQzPsp3l](https://user-images.githubusercontent.com/10239377/107079421-b3933a80-67a4-11eb-9e80-8105884da2b1.png)
![Code_mLStOexiH7](https://user-images.githubusercontent.com/10239377/107079426-b42bd100-67a4-11eb-9bff-f2a5350b9923.png)

**Comment by tarkah** [comment]
Works for very recent IPOs as well... here's a few from today / this past week:

![Code_LyP0LYSwiM](https://user-images.githubusercontent.com/10239377/107082060-7f217d80-67a8-11eb-8a41-f8fbd0be965e.png)
![Code_HdjXfSAUNP](https://user-images.githubusercontent.com/10239377/107082062-7fba1400-67a8-11eb-8497-943e8d7a65cc.png)

**Comment by Slickytail** [comment]
Awesome, thank you so much!

**Comment by tarkah** [comment]
No problem! I'll get a release out before Monday hopefully
