### ISSUE TITLE
Options shortcut 'o' doesn't work for cryptocurrency

### ISSUE THREAD

**Issue by miraclx** [tarkah/tickrs#49]
After seeing #34 & #37, I think, when you press <kbd>o</kbd> to view options for crypto, either a helpful dialog should be shown to the user or at least a note in the Help pane under the `Toggle Options Pane` section.

**Comment by miraclx** [comment]
Hi again, so what do you think about implementing a pop-up dialog informing users about the unavailability of options for crypto?

**Comment by tarkah** [comment]
I'm not really sure it's necessary. The Toggle block doesn't have the `Options 'o'` item in it when on a crypto tab, plus you've now added a notice on the help page.

**Comment by miraclx** [comment]
Oh. Just realized the toggle block doesn't include that. All good then.
