### ISSUE TITLE
Consistent OOMing at 5AM UTC

### ISSUE THREAD

**Issue by Komic** [tarkah/tickrs#61]
I'm running three instances of tickrs in a persistent tmux session. After noticing issues on my machine at 5AM a few days in a row (pretty much a complete crash this morning), I checked journalctl:

> Feb 10 06:02:20 kernel: Tasks state (memory values in pages):
> Feb 10 06:02:20 kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
> Feb 10 06:02:20 kernel: [2275268]     0 2275268  2001555   705854  9302016   421501             0 tickrs
> Feb 10 06:02:20 kernel: [2275331]     0 2275331  2149014   730901  9654272   434922             0 tickrs
> Feb 10 06:02:20 kernel: [2275401]     0 2275401  2050708   707631  9764864   475771             0 tickrs

They got killed in cascade over the next ten minutes, so I figure it leaks _fast_.

**Comment by tarkah** [comment]
I just rolled out a fix for this in #59, I'll be releasing shortly!

**Comment by Komic** [comment]
My bad, didn't realize #58 was the same bug, thanks! 👍

**Comment by tarkah** [comment]
No problem! New release is out with the fix:

https://github.com/tarkah/tickrs/releases/tag/v0.10.2
