### ISSUE TITLE
Allow reordering ticker tab entries

### ISSUE THREAD

**Issue by miraclx** [tarkah/tickrs#64]
Just a thought, but perhaps it would be nice to have the ability to reorder tabs after adding them.

This would reflect in the tabs view and also in the summary view.

Currently, you can move forward between tabs with the <kbd>tab</kbd> key, and in the inverse direction with the <kbd>shift</kbd>+<kbd>tab</kbd>.

However, (and maybe it's just me), I can also use the <kbd>ctrl</kbd> key with that to the same effect.

So a <kbd>ctrl</kbd>+<kbd>tab</kbd> has the same effect as a <kbd>tab</kbd>, and so does a <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>tab</kbd> have the same effect as a <kbd>shift</kbd>+<kbd>tab</kbd>.

Maybe the <kbd>ctrl</kbd> specifier can be used to signify reordering.

So a <kbd>ctrl</kbd>+<kbd>tab</kbd> would move a tab forward by an index, and a <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>tab</kbd> would move the selected tab and index backwards.

This is just a suggestion and the key specifiers can be anything, I just thought these appropriate since they're apparently redundant in effect and can be repurposed but can be a topic for discussion.

**Comment by tarkah** [comment]
I really like this idea! I've found myself removing tabs and readding them in the order I want, so this would be a nice improvement.

**Comment by miraclx** [comment]
For some extra info, here's what I get with the `SHOW_DEBUG=1` env.

<kbd>tab</kbd>

``` rust
DebugInfo { ..., last_event: Some(Key(KeyEvent { code: Tab, modifiers: NONE })), mode: DisplayStock }
```

<kbd>ctrl</kbd>+<kbd>tab</kbd>

``` rust
DebugInfo { ..., last_event: Some(Key(KeyEvent { code: Tab, modifiers: NONE })), mode: DisplayStock }
```

<kbd>shift</kbd>+<kbd>tab</kbd>

``` rust
DebugInfo { ..., last_event: Some(Key(KeyEvent { code: BackTab, modifiers: NONE })), mode: DisplayStock }
```

<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>tab</kbd>

``` rust
DebugInfo { ..., last_event: Some(Key(KeyEvent { code: BackTab, modifiers: NONE })), mode: DisplayStock }
```

It doesn't seem to register the <kbd>ctrl</kbd> key

**Comment by tarkah** [comment]
Does ctrl not work with other combinations?

**Comment by miraclx** [comment]
<kbd>ctrl</kbd>+<kbd>v</kbd>

```rust
DebugInfo { ..., last_event: Some(Key(KeyEvent { code: Char('v'), modifiers: CONTROL })), mode: DisplayStock }
```

So, it does

**Comment by tarkah** [comment]
I'm not at my computer right now, I'll test it tomorrow

**Comment by tarkah** [comment]
Yeah <kbd>ctrl</kbd>+<kbd>tab</kbd> doesn't work for me either, but I noticed the shortcut also gets captured by some terminals (like Windows Terminal), so I don't think it'd be a good fit anyways.

We could do <kbd>ctrl</kbd>+<kbd><-</kbd> and <kbd>ctrl</kbd>+<kbd>-></kbd> ?

**Comment by tarkah** [comment]
@miraclx I published this in the latest release, using ctrl+left / right made most sense. Works great!

**Comment by miraclx** [comment]
Love it! And your dedication to this is impeccable, keep it up!

**Comment by tarkah** [comment]
Awesome 🎉 It wouldn't be great or fun without involvement or suggestions from others, so thank you!
