### ISSUE TITLE
shift+tab not working

### ISSUE THREAD

**Issue by miraclx** [tarkah/tickrs#70]
After the latest dependency update #68, <kbd>shift</kbd>+<kbd>tab</kbd> no longer works.

With the `SHOW_DEBUG=1` env

`v0.11.0`
``` rust
DebugInfo { ..., last_event: Some(Key(KeyEvent { code: BackTab, modifiers: NONE })), mode: DisplayStock }
```

[`#68`](https://github.com/tarkah/tickrs/pull/68)
``` rust
DebugInfo { ..., last_event: Some(Key(KeyEvent { code: BackTab, modifiers: SHIFT })), mode: DisplayStock }
```

This was changed in `crossterm` [#490](https://github.com/crossterm-rs/crossterm/pull/490) and merged into master at https://github.com/crossterm-rs/crossterm/blob/423895e9523e8cfbd01c46f222c711c3a83bd784/src/event/sys/unix/parse.rs#L140

**Comment by tarkah** [comment]
Good catch!
