### ISSUE TITLE
Disable MouseCapture

### ISSUE THREAD

**Issue by miraclx** [tarkah/tickrs#72]
As at the moment of writing, *(4ba57c0)*, `tickrs` always captures the mouse despite only needing to show cursor location in the debug information.

Only, this debug information only shows with the `SHOW_DEBUG=1` env set

This effectively disallows all forms of text selection within `tickrs` whether in/out of debug mode.

Unless we can selectively enable capturing the mouse for certain parts of the interface *(maybe on the graphs for future purposes)*, we probably shouldn't at all since we aren't actually using it.

At this point you can't actually "copy" debug information, you would have to manually retype it.

**Comment by tarkah** [comment]
Yeah, this is an artifact of me wanting to see if I could enhance the stock widget with mouse interactivity. I never got around to it. I'll probably go with #74. Hopefully one day I can figure out some sort of feature to get OHLCV data to display wherever the mouse is located on the chart.

**Comment by miraclx** [comment]
+1

I've been nursing the idea of having a custom widget for displaying an interactive candlestick chart, but that would have to depend on that OHLCV data

I doubt we can only capture the mouse on interaction with the chart, allowing selection everywhere else, that would've been cool.

**Comment by tarkah** [comment]
So I have the OHLCV data, just need to figure out how to display it. There is a Canvas widget, so it should be possible to draw rectangles and lines for the candlestick. The harder part is grouping the data appropriately to fit whatever width the terminal is set to. I kind of have that figured out with the volumes graph so maybe its not as hard anymore. 



> I doubt we can only capture the mouse on interaction with the chart, allowing selection everywhere else, that would've been cool.

Yeah, we can call those execute! commands for mouse capturing when switching to / off whatever mode has the candlestick widget.

**Comment by miraclx** [comment]
<img src="https://i.pinimg.com/originals/6f/f0/d1/6ff0d1a0d9dfa09e4c645a8edea92498.png" width="30%">

It's no hurdle, let's go!

**Comment by miraclx** [comment]
> But anything else in view when that mode is active can't be selected, just not when the candlestick widget is in view.

we could maybe toggle chart selection with a special key, <kbd>M</kbd> *(mouse)*, <kbd>C</kbd> *(chart)*, <kbd>??</kbd>, so you can dynamically switch between those mouse modes

Unless there's a fullscreen chart view where we can enable mouse exclusively, there's currently a chart on every pane, summary, and stock view.

So, there could be a candlestick chart in the summary view too.

In which *"case"*, we'd need that key-bound toggle.

**Comment by tarkah** [comment]
Yeah I like the <kbd> M </kbd> hotkey to toggle mouse capture. I think it makes sense to also have a fullscreen view if candlestick is implemented to get as many pixels as possible towards rendering it. Then do some sort of overlay in the top left / right corner with the OHCLV data for wherever mouse position is at (this would be a phase 2 add). 

I'm skeptical candlesticks would look like anything in summary view due to the restricted height. The min / max / median / Q1 / Q3 may all be within 1-2 "braille" dots of each other. But this is something I can easily test once I have the chart type figured out.

**Comment by tarkah** [comment]
FYI, I have a discussion around this from someone else who previously requested a candlestick chart. We should carry out further conversation there.

https://github.com/tarkah/tickrs/discussions/30
