### ISSUE TITLE
Theme: background isn't applied everywhere

### ISSUE THREAD

**Issue by miraclx** [tarkah/tickrs#81]
Just tried the background theming option for the first time

<details>
<summary> <code> ~/.config/tickrs/config.yml </code> </summary>

```yml
theme:
  background: '#403E41'
```

</details>

| | line | candle |
| - | - | - |
| summary of 1 | ![Screenshot_20210220_191115](https://user-images.githubusercontent.com/16881812/108604653-7edfcf80-73af-11eb-96e2-3b89909f1ca9.png) | ![Screenshot_20210220_190458](https://user-images.githubusercontent.com/16881812/108604488-95d1f200-73ae-11eb-8780-c1537af2730a.png) |
| summary of 3 | ![Screenshot_20210220_191301](https://user-images.githubusercontent.com/16881812/108604688-b77fa900-73af-11eb-84eb-44ade54af117.png) | ![Screenshot_20210220_190139](https://user-images.githubusercontent.com/16881812/108604438-41c70d80-73ae-11eb-8ace-bbe6e396cf4e.png)
| stock view | ![Screenshot_20210220_191435](https://user-images.githubusercontent.com/16881812/108604720-eac23800-73af-11eb-9dab-aa8a0037e4ab.png) | ![Screenshot_20210220_190300](https://user-images.githubusercontent.com/16881812/108604442-4db2cf80-73ae-11eb-8aa0-0bf815da468d.png) |

**Comment by tarkah** [comment]
Ahh, I never tested theming on the new candle chart. My bad! I should implement my own default style that always uses our Theme background color so I don't have to always remember to specify it.

**Comment by miraclx** [comment]
Also, in summary mode (irrespective of line or candle views), the background isn't applied where there isn't a block showing an item. As shown above.

And the time frame tabs below in the summary view doesn't have a background too (unlike stock mode).

**Comment by tarkah** [comment]
> 
> 
> Also, in summary mode (irrespective of line or candle views), the background isn't applied where there isn't a block showing an item. As shown above.
> 
> And the time frame tabs below in the summary view doesn't have a background too (unlike stock mode).

Yeah I know exactly what I did to break this from the initial theme release. I'll add a styling change that'll future proof me from making these errors again in the future.
