### ISSUE TITLE
Most recent date is wrong in candle view for longer time periods

### ISSUE THREAD

**Issue by fspoettel** [tarkah/tickrs#83]
In candle view, the right-most date displays incorrectly for the larger charts. (`1W` and up)

The 1W chart displays `01-01 01:00`:
![image](https://user-images.githubusercontent.com/1682504/108609657-a34ba400-73cf-11eb-91d5-a1ad4fe438b9.png)

The 1M+ charts display `1970-01-01`:
![image](https://user-images.githubusercontent.com/1682504/108609674-c24a3600-73cf-11eb-977d-eff8a295dd74.png)

Not sure if this might be relevant: my local timezone is `Europe/Berlin`.

**Comment by tarkah** [comment]
At that's 0 in unix timestamp :) I know the issue here, I'll easily be able to fix this.
